CREATE TABLE IF NOT EXISTS project_scopes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  scope_title VARCHAR(255) NOT NULL,
  scope_description TEXT NOT NULL,
  business_objectives TEXT NULL,
  in_scope TEXT NULL,
  out_of_scope TEXT NULL,
  assumptions TEXT NULL,
  dependencies TEXT NULL,
  status ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REWORK_REQUIRED') NOT NULL DEFAULT 'DRAFT',
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  review_comments TEXT NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_project_scopes_request FOREIGN KEY (request_id) REFERENCES requests(id),
  CONSTRAINT fk_project_scopes_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_project_scopes_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id),
  INDEX idx_project_scopes_request_status (request_id, status),
  INDEX idx_project_scopes_created_by (created_by_user_id),
  INDEX idx_project_scopes_reviewed_by (reviewed_by_user_id)
);
