CREATE TABLE IF NOT EXISTS sprints (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  sprint_name VARCHAR(180) NOT NULL,
  goal TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  estimated_hours DECIMAL(10,2) NULL,
  actual_hours DECIMAL(10,2) NULL,
  status ENUM('PLANNED', 'CREATED', 'ACTIVE', 'BLOCKED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PLANNED',
  assigned_developer_user_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  started_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_sprints_request FOREIGN KEY (request_id) REFERENCES requests(id),
  CONSTRAINT fk_sprints_assigned_developer FOREIGN KEY (assigned_developer_user_id) REFERENCES users(id),
  CONSTRAINT fk_sprints_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  INDEX idx_sprints_request_status (request_id, status),
  INDEX idx_sprints_assigned_developer (assigned_developer_user_id),
  INDEX idx_sprints_created_by (created_by_user_id),
  INDEX idx_sprints_dates (start_date, end_date)
);
