ALTER TABLE requests
  MODIFY status ENUM(
    'SUBMITTED',
    'DEPARTMENT_APPROVAL_PENDING',
    'CLARIFICATION_REQUESTED',
    'DEPARTMENT_REJECTED',
    'IT_REVIEW_PENDING',
    'IT_REJECTED',
    'DEFERRED',
    'ASSIGNMENT_PENDING',
    'ASSIGNED',
    'IN_DEVELOPMENT',
    'DEVELOPMENT_COMPLETE',
    'IN_TESTING',
    'TEST_FAILED',
    'UAT_PENDING',
    'UAT_REJECTED',
    'CLOSED',
    'PM_ASSIGNED',
    'SCOPE_REVIEW',
    'USER_STORY_REVIEW',
    'REQUIREMENTS_DEPARTMENT_REVIEW',
    'REQUIREMENTS_IT_REVIEW',
    'REQUIREMENTS_CLARIFICATION_REQUESTED',
    'REQUIREMENTS_APPROVED',
    'DEVELOPER_ASSIGNED',
    'SPRINT_PLANNING',
    'QA_PENDING',
    'QA_FAILED',
    'QA_PASSED',
    'UAT_FAILED',
    'UAT_APPROVED',
    'DEPLOYMENT_PENDING',
    'DEPLOYED'
  ) NOT NULL DEFAULT 'SUBMITTED';

CREATE TABLE IF NOT EXISTS requirement_revisions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  revision_number INT UNSIGNED NOT NULL,
  status ENUM('DRAFT', 'UNDER_DEPARTMENT_REVIEW', 'UNDER_PM_REVIEW', 'UNDER_IT_REVIEW', 'CLARIFICATION_REQUESTED', 'APPROVED', 'SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
  pending_reviewer_role_code ENUM('DEPARTMENT_HEAD', 'IT_HEAD', 'PROJECT_MANAGER') NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  submitted_by_user_id BIGINT UNSIGNED NULL,
  submitted_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  superseded_at TIMESTAMP NULL,
  change_summary TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_requirement_revisions_request FOREIGN KEY (request_id) REFERENCES requests(id),
  CONSTRAINT fk_requirement_revisions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT fk_requirement_revisions_submitted_by FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
  UNIQUE KEY uq_requirement_revisions_request_number (request_id, revision_number),
  INDEX idx_requirement_revisions_request_status (request_id, status),
  INDEX idx_requirement_revisions_pending_role (pending_reviewer_role_code)
);

CREATE TABLE IF NOT EXISTS requirement_artifact_snapshots (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  revision_id BIGINT UNSIGNED NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  artifact_type ENUM('SCOPE', 'USER_STORY') NOT NULL,
  artifact_id BIGINT UNSIGNED NOT NULL,
  content_json JSON NOT NULL,
  content_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_requirement_snapshots_revision FOREIGN KEY (revision_id) REFERENCES requirement_revisions(id),
  CONSTRAINT fk_requirement_snapshots_request FOREIGN KEY (request_id) REFERENCES requests(id),
  UNIQUE KEY uq_requirement_snapshots_artifact (revision_id, artifact_type, artifact_id),
  INDEX idx_requirement_snapshots_request (request_id),
  INDEX idx_requirement_snapshots_hash (content_hash)
);

CREATE TABLE IF NOT EXISTS requirement_reviews (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  revision_id BIGINT UNSIGNED NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  reviewer_role_code ENUM('DEPARTMENT_HEAD', 'PROJECT_MANAGER', 'IT_HEAD') NOT NULL,
  reviewer_user_id BIGINT UNSIGNED NULL,
  decision ENUM('PENDING', 'APPROVED', 'CHANGES_REQUESTED') NOT NULL DEFAULT 'PENDING',
  comments TEXT NULL,
  decided_at TIMESTAMP NULL,
  invalidated_at TIMESTAMP NULL,
  invalidated_by_revision_id BIGINT UNSIGNED NULL,
  is_current BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_requirement_reviews_revision FOREIGN KEY (revision_id) REFERENCES requirement_revisions(id),
  CONSTRAINT fk_requirement_reviews_request FOREIGN KEY (request_id) REFERENCES requests(id),
  CONSTRAINT fk_requirement_reviews_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users(id),
  CONSTRAINT fk_requirement_reviews_invalidated_by FOREIGN KEY (invalidated_by_revision_id) REFERENCES requirement_revisions(id),
  UNIQUE KEY uq_requirement_reviews_revision_role (revision_id, reviewer_role_code),
  INDEX idx_requirement_reviews_request_current (request_id, is_current),
  INDEX idx_requirement_reviews_decision (decision)
);

CREATE TABLE IF NOT EXISTS requirement_change_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  revision_id BIGINT UNSIGNED NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  artifact_type ENUM('SCOPE', 'USER_STORY', 'REQUIREMENTS') NOT NULL,
  artifact_id BIGINT UNSIGNED NULL,
  changed_by_user_id BIGINT UNSIGNED NOT NULL,
  change_type ENUM('CREATED', 'UPDATED', 'SUBMITTED', 'APPROVED', 'CHANGES_REQUESTED', 'CLARIFICATION_REQUESTED', 'CLARIFICATION_RESPONDED', 'INVALIDATED') NOT NULL,
  field_name VARCHAR(100) NULL,
  old_value TEXT NULL,
  new_value TEXT NULL,
  change_summary TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_requirement_changes_revision FOREIGN KEY (revision_id) REFERENCES requirement_revisions(id),
  CONSTRAINT fk_requirement_changes_request FOREIGN KEY (request_id) REFERENCES requests(id),
  CONSTRAINT fk_requirement_changes_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id),
  INDEX idx_requirement_changes_revision (revision_id, created_at),
  INDEX idx_requirement_changes_request (request_id, created_at),
  INDEX idx_requirement_changes_user (changed_by_user_id)
);
