-- PM <-> Department HOD revision-based requirements review workflow.

ALTER TABLE requests
  MODIFY status ENUM(
    'SUBMITTED',
    'DEPARTMENT_APPROVAL_PENDING',
    'CLARIFICATION_REQUESTED',
    'DEPARTMENT_REJECTED',
    'IT_REVIEW_PENDING',
    'IT_REJECTED',
    'DEFERRED',
    'ASSIGNMENT_PENDING',
    'ASSIGNED',
    'IN_DEVELOPMENT',
    'DEVELOPMENT_COMPLETE',
    'IN_TESTING',
    'TEST_FAILED',
    'UAT_PENDING',
    'UAT_REJECTED',
    'CLOSED',
    'PM_ASSIGNED',
    'SCOPE_REVIEW',
    'USER_STORY_REVIEW',
    'REQUIREMENTS_DEPARTMENT_REVIEW',
    'REQUIREMENTS_PM_REVIEW',
    'REQUIREMENTS_IT_REVIEW',
    'REQUIREMENTS_CLARIFICATION_REQUESTED',
    'REQUIREMENTS_APPROVED',
    'DEVELOPER_ASSIGNED',
    'SPRINT_PLANNING',
    'SPRINT_CREATED',
    'SPRINT_ACTIVE',
    'QA_PENDING',
    'QA_FAILED',
    'QA_PASSED',
    'UAT_FAILED',
    'UAT_APPROVED',
    'DEPLOYMENT_PENDING',
    'DEPLOYED'
  ) NOT NULL DEFAULT 'SUBMITTED';

ALTER TABLE requirement_revisions
  MODIFY status ENUM(
    'DRAFT',
    'UNDER_DEPARTMENT_REVIEW',
    'UNDER_PM_REVIEW',
    'UNDER_IT_REVIEW',
    'CLARIFICATION_REQUESTED',
    'APPROVED',
    'SUPERSEDED'
  ) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE requirement_reviews
  MODIFY reviewer_role_code ENUM('DEPARTMENT_HEAD', 'PROJECT_MANAGER', 'IT_HEAD') NOT NULL;
